sudo: required
services:
  - docker
# before our tests run
before_install:
  - docker build -t shreyasshettigar/docker-react -f Dockerfile.dev .
script:
  - docker run shreyasshettigar/docker-react npm run test -- --coverage
  
# After setting travis CI and setting AWS elasticbeanstalk instance
