---
before_install:
  - "docker build -t shreyasshettigar/docker-react -f Dockerfile.dev ."
script:
  - "docker run shreyasshettigar/docker-react npm run test -- --coverage"
services:
  - docker
sudo: required
